//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagementSystem {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseManagementSystem.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить позицию.
        /// </summary>
        public static string AddItemButton {
            get {
                return ResourceManager.GetString("AddItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы один товар.
        /// </summary>
        public static string AddProductsFirst {
            get {
                return ResourceManager.GetString("AddProductsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте товары в отгрузку.
        /// </summary>
        public static string AddProductsToShipment {
            get {
                return ResourceManager.GetString("AddProductsToShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление товара.
        /// </summary>
        public static string AddProductTitle {
            get {
                return ResourceManager.GetString("AddProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string ArticleHeader {
            get {
                return ResourceManager.GetString("ArticleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название категории.
        /// </summary>
        public static string CategoryNameError {
            get {
                return ResourceManager.GetString("CategoryNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провести отгрузку.
        /// </summary>
        public static string ConfirmShipmentButton {
            get {
                return ResourceManager.GetString("ConfirmShipmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}Подтвердить отгрузку? Товары будут списаны..
        /// </summary>
        public static string ConfirmShipmentMessage {
            get {
                return ResourceManager.GetString("ConfirmShipmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string ConfirmShipmentTitle {
            get {
                return ResourceManager.GetString("ConfirmShipmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списать выбранные товары ({0} позиций)?.
        /// </summary>
        public static string ConfirmWriteOffSelected {
            get {
                return ResourceManager.GetString("ConfirmWriteOffSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла критическая ошибка: {0}.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить категорию &apos;{0}&apos;? {1}.
        /// </summary>
        public static string DeleteCategoryConfirm {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить товар &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteProductConfirm {
            get {
                return ResourceManager.GetString("DeleteProductConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование товара.
        /// </summary>
        public static string EditProductTitle {
            get {
                return ResourceManager.GetString("EditProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара!.
        /// </summary>
        public static string EnterArticle {
            get {
                return ResourceManager.GetString("EnterArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название товара!.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите единицу измерения!.
        /// </summary>
        public static string EnterUnit {
            get {
                return ResourceManager.GetString("EnterUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректную цену!.
        /// </summary>
        public static string EnterValidPrice {
            get {
                return ResourceManager.GetString("EnterValidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество.
        /// </summary>
        public static string EnterValidQuantity {
            get {
                return ResourceManager.GetString("EnterValidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: {0}.
        /// </summary>
        public static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных для экспорта. Сначала сформируйте отчёт..
        /// </summary>
        public static string ExportNoData {
            get {
                return ResourceManager.GetString("ExportNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция экспорта будет добавлена позже..
        /// </summary>
        public static string ExportNotImplemented {
            get {
                return ResourceManager.GetString("ExportNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт отчёта.
        /// </summary>
        public static string ExportReportTitle {
            get {
                return ResourceManager.GetString("ExportReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите формат экспорта: Да - Excel Нет - PDF.
        /// </summary>
        public static string ExportSelectFormat {
            get {
                return ResourceManager.GetString("ExportSelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчёт сохранён в Excel!.
        /// </summary>
        public static string ExportSuccessExcel {
            get {
                return ResourceManager.GetString("ExportSuccessExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчёт сохранён в PDF!.
        /// </summary>
        public static string ExportSuccessPdf {
            get {
                return ResourceManager.GetString("ExportSuccessPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: {0}.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка {0}: артикул &apos;{1}&apos; не найден.
        /// </summary>
        public static string ImportArticleNotFound {
            get {
                return ResourceManager.GetString("ImportArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт завершён Добавлено: {0} Ошибок: {1}.
        /// </summary>
        public static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка {0}: должно быть 3 колонки (артикул;количество;цена).
        /// </summary>
        public static string ImportCsvWrongColumns {
            get {
                return ResourceManager.GetString("ImportCsvWrongColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка {0}: неправильная цена &apos;{1}&apos;.
        /// </summary>
        public static string ImportInvalidPrice {
            get {
                return ResourceManager.GetString("ImportInvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка {0}: неправильное количество &apos;{1}&apos;.
        /// </summary>
        public static string ImportInvalidQuantity {
            get {
                return ResourceManager.GetString("ImportInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужен файл .csv или .xlsx.
        /// </summary>
        public static string ImportWrongFormat {
            get {
                return ResourceManager.GetString("ImportWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара. Доступно: {0}.
        /// </summary>
        public static string InsufficientStock {
            get {
                return ResourceManager.GetString("InsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе. Не хватает: {0}.
        /// </summary>
        public static string InsufficientStockRemaining {
            get {
                return ResourceManager.GetString("InsufficientStockRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списано {0} шт. товара {1} (FIFO).
        /// </summary>
        public static string ItemsWrittenOffFifo {
            get {
                return ResourceManager.GetString("ItemsWrittenOffFifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список обновлён.
        /// </summary>
        public static string ListRefreshed {
            get {
                return ResourceManager.GetString("ListRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки: {0}.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформление новой отгрузки.
        /// </summary>
        public static string NewShipmentTitle {
            get {
                return ResourceManager.GetString("NewShipmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет партий товара для списания.
        /// </summary>
        public static string NoBatchesForWriteOff {
            get {
                return ResourceManager.GetString("NoBatchesForWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За выбранный период отгрузок не найдено..
        /// </summary>
        public static string NoShipmentsFound {
            get {
                return ResourceManager.GetString("NoShipmentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка PostgreSQL: {0} Таблица: {1} Подробности: {2}.
        /// </summary>
        public static string PostgresError {
            get {
                return ResourceManager.GetString("PostgresError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string PriceHeader {
            get {
                return ResourceManager.GetString("PriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена должна быть больше нуля!.
        /// </summary>
        public static string PriceMustBePositive {
            get {
                return ResourceManager.GetString("PriceMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен товар: ID={0}, Название={1}.
        /// </summary>
        public static string ProductAddedInfo {
            get {
                return ResourceManager.GetString("ProductAddedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено: {0} - {1} шт..
        /// </summary>
        public static string ProductAddedToShipment {
            get {
                return ResourceManager.GetString("ProductAddedToShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот товар уже добавлен.
        /// </summary>
        public static string ProductAlreadyAdded {
            get {
                return ResourceManager.GetString("ProductAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот товар уже добавлен в отгрузку.
        /// </summary>
        public static string ProductAlreadyInShipment {
            get {
                return ResourceManager.GetString("ProductAlreadyInShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено товаров с остатками: {0}.
        /// </summary>
        public static string ProductsLoaded {
            get {
                return ResourceManager.GetString("ProductsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно обновлен!.
        /// </summary>
        public static string ProductUpdatedSuccess {
            get {
                return ResourceManager.GetString("ProductUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        public static string QuantityHeader {
            get {
                return ResourceManager.GetString("QuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество должно быть больше нуля.
        /// </summary>
        public static string QuantityMustBePositive {
            get {
                return ResourceManager.GetString("QuantityMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка формирования отчёта: {0}.
        /// </summary>
        public static string ReportGenerationError {
            get {
                return ResourceManager.GetString("ReportGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении: {0}.
        /// </summary>
        public static string SaveErrorWithDetails {
            get {
                return ResourceManager.GetString("SaveErrorWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товары для списания.
        /// </summary>
        public static string SelectItemsToWriteOff {
            get {
                return ResourceManager.GetString("SelectItemsToWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите позицию для удаления.
        /// </summary>
        public static string SelectItemToDelete {
            get {
                return ResourceManager.GetString("SelectItemToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар из списка.
        /// </summary>
        public static string SelectProductFromList {
            get {
                return ResourceManager.GetString("SelectProductFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар из списка остатков.
        /// </summary>
        public static string SelectProductFromStock {
            get {
                return ResourceManager.GetString("SelectProductFromStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор товара и количества.
        /// </summary>
        public static string SelectProductTitle {
            get {
                return ResourceManager.GetString("SelectProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сохранены!.
        /// </summary>
        public static string SettingsSavedSuccess {
            get {
                return ResourceManager.GetString("SettingsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения: {0}.
        /// </summary>
        public static string SettingsSaveError {
            get {
                return ResourceManager.GetString("SettingsSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка №{0} проведена!.
        /// </summary>
        public static string ShipmentCompleted {
            get {
                return ResourceManager.GetString("ShipmentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создана отгрузка ID={0}.
        /// </summary>
        public static string ShipmentCreated {
            get {
                return ResourceManager.GetString("ShipmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остаток.
        /// </summary>
        public static string StockHeader {
            get {
                return ResourceManager.GetString("StockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список остатков обновлен.
        /// </summary>
        public static string StockRefreshed {
            get {
                return ResourceManager.GetString("StockRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставка успешно сохранена!.
        /// </summary>
        public static string SupplySavedSuccess {
            get {
                return ResourceManager.GetString("SupplySavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакция завершена!.
        /// </summary>
        public static string TransactionCompleted {
            get {
                return ResourceManager.GetString("TransactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ед. изм..
        /// </summary>
        public static string UnitHeader {
            get {
                return ResourceManager.GetString("UnitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обновления: {0}.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка.
        /// </summary>
        public static string UserCheckTitle {
            get {
                return ResourceManager.GetString("UserCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID пользователя: {0} Имя: {1}.
        /// </summary>
        public static string UserInfoMessage {
            get {
                return ResourceManager.GetString("UserInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: пользователь не авторизован!.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка списания {0}: {1}.
        /// </summary>
        public static string WriteOffError {
            get {
                return ResourceManager.GetString("WriteOffError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списано товаров: {0} из {1}.
        /// </summary>
        public static string WriteOffResult {
            get {
                return ResourceManager.GetString("WriteOffResult", resourceCulture);
            }
        }
    }
}
